/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/demo/actors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Identitas siap pakai untuk pemilih peran
         * @description Pengganti login selama autentikasi berada di luar cakupan PoC. Id yang dikembalikan dipakai sebagai header X-Actor-Id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["internal_modules_reference.DemoActorResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspection-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar jenis inspeksi yang masih ditawarkan */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["internal_modules_reference.InspectionTypeResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar inspektor aktif beserta jumlah penugasan berjalan */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["internal_modules_reference.InspectorResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar job order
         * @description Klien otomatis hanya melihat order milik perusahaannya sendiri, apa pun isi company_id.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Halaman */
                    page?: number;
                    /** @description Jumlah data per halaman */
                    limit?: number;
                    /** @description Cari ref/objek/lokasi/kota */
                    search?: string;
                    /** @description Saring status */
                    status?: "requested" | "assigned" | "on_the_way" | "on_site" | "in_progress" | "completed" | "failed" | "cancelled";
                    /** @description Saring perusahaan */
                    company_id?: string;
                    /** @description Saring inspektor */
                    inspector_id?: string;
                    /** @description Saringan layar koordinator */
                    attention?: "penugasan" | "pembatalan" | "basi" | "terlambat";
                };
                header: {
                    /** @description Id pengguna yang bertindak */
                    "X-Actor-Id": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["verifield-be_internal_modules_joborder_dto.JobOrderResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Buat permintaan inspeksi baru */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Id pengguna yang bertindak */
                    "X-Actor-Id": string;
                };
                path?: never;
                cookie?: never;
            };
            /** @description Data permintaan */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["verifield-be_internal_modules_joborder_dto.CreateJobOrderDTO"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["verifield-be_internal_modules_joborder_dto.JobOrderResponse"];
                        };
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail job order beserta riwayat status */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Id pengguna yang bertindak */
                    "X-Actor-Id": string;
                };
                path: {
                    /** @description Job order ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["verifield-be_internal_modules_joborder_dto.JobOrderResponse"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tugaskan inspektor
         * @description expected_version wajib; bila order sudah berubah, permintaan ditolak dengan 409 (keputusan B-09).
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Id pengguna yang bertindak */
                    "X-Actor-Id": string;
                };
                path: {
                    /** @description Job order ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Inspektor dan versi yang diharapkan */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["verifield-be_internal_modules_joborder_dto.AssignInspectorDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["verifield-be_internal_modules_joborder_dto.JobOrderResponse"];
                        };
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batalkan atau ajukan pembatalan
         * @description Hasilnya bergantung pada tahap dan peran. Setelah pekerjaan dimulai, pembatalan oleh klien menjadi permintaan yang menunggu koordinator (keputusan B-05).
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Id pengguna yang bertindak */
                    "X-Actor-Id": string;
                };
                path: {
                    /** @description Job order ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Alasan pembatalan */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["verifield-be_internal_modules_joborder_dto.CancelJobOrderDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["verifield-be_internal_modules_joborder_dto.CancelResult"];
                        };
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/cancellations/{requestId}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Putuskan permintaan pembatalan */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Id pengguna yang bertindak */
                    "X-Actor-Id": string;
                };
                path: {
                    /** @description Job order ID (UUID) */
                    id: string;
                    /** @description Cancellation request ID (UUID) */
                    requestId: string;
                };
                cookie?: never;
            };
            /** @description Keputusan koordinator */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["verifield-be_internal_modules_joborder_dto.DecideCancellationDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["verifield-be_internal_modules_joborder_dto.JobOrderResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/cancellations/{requestId}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Putuskan penyelesaian komersial
         * @description Dipakai ketika pekerjaan terlanjur selesai mendahului keputusan pembatalan. Status order tidak berubah; yang dicatat adalah siapa menanggung biayanya (keputusan B-10).
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Id pengguna yang bertindak */
                    "X-Actor-Id": string;
                };
                path: {
                    /** @description Job order ID (UUID) */
                    id: string;
                    /** @description Cancellation request ID (UUID) */
                    requestId: string;
                };
                cookie?: never;
            };
            /** @description Hasil penyelesaian beserta catatannya */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["verifield-be_internal_modules_joborder_dto.SettleCancellationDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["verifield-be_internal_modules_joborder_dto.JobOrderResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Koreksi status oleh koordinator
         * @description Boleh mundur ke tahap sebelumnya, wajib beralasan, dan tercatat sebagai entri baru — riwayat tidak pernah ditimpa (keputusan B-06).
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Id pengguna yang bertindak */
                    "X-Actor-Id": string;
                };
                path: {
                    /** @description Job order ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Status hasil koreksi beserta alasannya */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["verifield-be_internal_modules_joborder_dto.CorrectStatusDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["verifield-be_internal_modules_joborder_dto.JobOrderResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Riwayat status satu job order
         * @description after_seq memutar ulang hanya perubahan yang lebih baru dari kursor yang dipegang klien.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Kursor seq terakhir yang sudah dimiliki klien */
                    after_seq?: number;
                };
                header: {
                    /** @description Id pengguna yang bertindak */
                    "X-Actor-Id": string;
                };
                path: {
                    /** @description Job order ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["verifield-be_internal_modules_joborder_dto.JobStatusEventResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Perbarui status dari lapangan
         * @description Idempoten lewat client_event_id. Pembaruan yang ditolak tetap menghasilkan 200 karena pengirimannya berhasil — yang gagal adalah perubahan statusnya (keputusan B-07).
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Id pengguna yang bertindak */
                    "X-Actor-Id": string;
                };
                path: {
                    /** @description Job order ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Status baru beserta penanda unik perangkat */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["verifield-be_internal_modules_joborder_dto.SubmitStatusEventDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["verifield-be_internal_modules_joborder_dto.SubmitStatusEventResult"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Berbeda dari health check: probe ini menyentuh database, dan menjawab 503 selama database belum terjangkau.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream perubahan job order (SSE)
         * @description Mengirim keadaan terkini setiap order yang berubah. Cakupan ditentukan peran pemanggil. Saat menyambung ulang, browser mengirim Last-Event-ID sendiri; pada koneksi pertama klien menyertakan last_event_id lewat query.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Kursor seq terakhir yang sudah dimiliki klien */
                    last_event_id?: number;
                };
                header: {
                    /** @description Id pengguna yang bertindak */
                    "X-Actor-Id": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description aliran text/event-stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar user
         * @description Mengambil daftar user dengan paginasi, pencarian, dan sorting
         */
        get: {
            parameters: {
                query?: {
                    /** @description Halaman */
                    page?: number;
                    /** @description Jumlah data per halaman */
                    limit?: number;
                    /** @description Cari berdasarkan nama/email */
                    search?: string;
                    /** @description Kolom sorting */
                    sort_by?: "created_at" | "updated_at" | "name" | "email" | "role";
                    /** @description Arah sorting */
                    sort_dir?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["verifield-be_internal_modules_user_dto.UserResponse"][];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"];
                    };
                };
            };
        };
        put?: never;
        /** Buat user baru */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Data user */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["verifield-be_internal_modules_user_dto.CreateUserDTO"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["verifield-be_internal_modules_user_dto.UserResponse"];
                        };
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["verifield-be_internal_modules_user_dto.UserResponse"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Hapus user */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Perbarui user */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Field yang ingin diubah */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["verifield-be_internal_modules_user_dto.UpdateUserDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"] & {
                            data?: components["schemas"]["verifield-be_internal_modules_user_dto.UserResponse"];
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["verifield-be_internal_common_response.Envelope"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "internal_modules_reference.DemoActorResponse": {
            company_id?: string;
            company_name?: string;
            email?: string;
            id?: string;
            name?: string;
            /** @enum {string} */
            role?: "admin" | "client" | "inspector" | "cs";
        };
        "internal_modules_reference.InspectionTypeResponse": {
            /** @example bulk_cargo */
            code?: string;
            id?: string;
            /** @example Inspeksi Kargo Curah */
            name?: string;
        };
        "internal_modules_reference.InspectorResponse": {
            active_jobs?: number;
            email?: string;
            id?: string;
            name?: string;
        };
        "verifield-be_internal_common_apperror.FieldError": {
            /** @example email */
            field?: string;
            /** @example email wajib diisi */
            message?: string;
        };
        "verifield-be_internal_common_response.Envelope": {
            code?: string;
            data?: unknown;
            errors?: components["schemas"]["verifield-be_internal_common_apperror.FieldError"][];
            message?: string;
            meta?: components["schemas"]["verifield-be_internal_common_response.Meta"];
            success?: boolean;
        };
        "verifield-be_internal_common_response.Meta": {
            /** @example 10 */
            limit?: number;
            /** @example 1 */
            page?: number;
            /** @example 42 */
            total?: number;
            /** @example 5 */
            total_page?: number;
        };
        "verifield-be_internal_modules_joborder_dto.AssignInspectorDTO": {
            /** @example 1 */
            expected_version: number;
            inspector_id: string;
        };
        "verifield-be_internal_modules_joborder_dto.CancelJobOrderDTO": {
            /**
             * @description Kosong berarti pemanggil tidak peduli pada versi. Diisi oleh koordinator
             *     yang bertindak dari layar yang mungkin sudah basi.
             */
            expected_version?: number;
            /** @example Jadwal pengapalan dimajukan */
            reason: string;
        };
        "verifield-be_internal_modules_joborder_dto.CancelResult": {
            /**
             * @example travel
             * @enum {string}
             */
            fee?: "none" | "travel" | "visit" | "coordinator";
            message?: string;
            order?: components["schemas"]["verifield-be_internal_modules_joborder_dto.JobOrderResponse"];
            /**
             * @example cancelled
             * @enum {string}
             */
            status?: "cancelled" | "pending_approval";
        };
        "verifield-be_internal_modules_joborder_dto.CorrectStatusDTO": {
            expected_version: number;
            /** @example Inspektor salah menekan Selesai padahal baru tiba */
            reason: string;
            /** @enum {string} */
            to_status: "requested" | "assigned" | "on_the_way" | "on_site" | "in_progress" | "completed" | "failed" | "cancelled";
        };
        "verifield-be_internal_modules_joborder_dto.CreateJobOrderDTO": {
            /** @example Jakarta */
            city: string;
            /** @example 6f1e6f0c-6f2a-4c5e-9f3a-0b6b1a4d2c11 */
            inspection_type_id: string;
            /** @example Jl. Palmerah No. 1, Jakarta Utara */
            location_address: string;
            /** @example Dermaga 3, Pelabuhan Tanjung Priok */
            location_name: string;
            /** @example Batu bara 5.000 MT */
            object_description: string;
            scheduled_end_at: string;
            scheduled_start_at: string;
        };
        "verifield-be_internal_modules_joborder_dto.DecideCancellationDTO": {
            /**
             * @example approve
             * @enum {string}
             */
            decision: "approve" | "reject";
            note?: string;
        };
        "verifield-be_internal_modules_joborder_dto.JobOrderResponse": {
            cancellation_requested?: boolean;
            city?: string;
            company_id?: string;
            /** @example PT Karya Bahari Ekspor */
            company_name?: string;
            created_at?: string;
            created_by_name?: string;
            /**
             * @example in_progress
             * @enum {string}
             */
            current_status?: "requested" | "assigned" | "on_the_way" | "on_site" | "in_progress" | "completed" | "failed" | "cancelled";
            /** @description Hanya terisi pada endpoint detail; daftar tidak membawa riwayat. */
            events?: components["schemas"]["verifield-be_internal_modules_joborder_dto.JobStatusEventResponse"][];
            /**
             * @description Tahap terjauh yang sempat dicapai sebelum order berakhir. Untuk order yang
             *     masih berjalan nilainya sama dengan current_status; untuk yang dibatalkan
             *     atau gagal, inilah yang menjawab "sejauh mana sempat berjalan".
             *
             *     Dihitung server karena daftar order sengaja tidak membawa riwayat, dan
             *     justru di daftar itulah pertanyaan tersebut paling sering muncul.
             * @enum {string}
             */
            exit_status?: "requested" | "assigned" | "on_the_way" | "on_site" | "in_progress" | "completed" | "failed" | "cancelled";
            has_open_alert?: boolean;
            id?: string;
            inspection_type_id?: string;
            /** @example Inspeksi Kargo Curah */
            inspection_type_name?: string;
            inspector_id?: string;
            inspector_name?: string;
            location_address?: string;
            location_name?: string;
            object_description?: string;
            /**
             * @description Jenis alert yang masih terbuka, karena kalimat yang harus dibaca
             *     koordinator berbeda per jenis.
             *
             *     NOTE: pekerjaan yang selesai mendahului keputusan pembatalan TIDAK
             *     memakai alert. Permintaannya sendiri yang berpindah menunggu penyelesaian
             *     dan tetap berada di antrean koordinator (B-10) — satu keadaan cukup satu
             *     mekanisme.
             * @enum {string}
             */
            open_alert_type?: "late_update_rejected";
            /**
             * @description Hanya terisi pada endpoint detail. Koordinator butuh id-nya untuk
             *     memutuskan, dan alasannya untuk memutuskan dengan benar.
             */
            pending_cancellation?: components["schemas"]["verifield-be_internal_modules_joborder_dto.PendingCancellation"];
            /** @example JO-2026-0001 */
            reference_number?: string;
            scheduled_end_at?: string;
            scheduled_start_at?: string;
            /**
             * @description Seq event terakhir milik order ini. Klien memakainya untuk mengabaikan
             *     pesan real-time yang lebih tua daripada yang sudah diterapkan, sehingga
             *     jaminan urutan berlaku di dua sisi — bukan hanya di server.
             */
            seq?: number;
            status_changed_at?: string;
            updated_at?: string;
            /** @description Dikirim balik saat mutasi sebagai expected_version (keputusan B-09). */
            version?: number;
        };
        "verifield-be_internal_modules_joborder_dto.JobStatusEventResponse": {
            /**
             * @description Keputusan B-07: event yang ditolak tetap tersimpan. Hanya event
             *     Accepted=true yang pernah mengubah status.
             */
            accepted?: boolean;
            actor_id?: string;
            /** @example Rina Amelia */
            actor_name?: string;
            /**
             * @example inspector
             * @enum {string}
             */
            actor_role?: "admin" | "client" | "inspector" | "cs";
            client_event_id?: string;
            created_at?: string;
            /**
             * @example on_site
             * @enum {string}
             */
            from_status?: "requested" | "assigned" | "on_the_way" | "on_site" | "in_progress" | "completed" | "failed" | "cancelled";
            /** @example 6f1e6f0c-6f2a-4c5e-9f3a-0b6b1a4d2c11 */
            id?: string;
            is_correction?: boolean;
            job_order_id?: string;
            /**
             * @description Keputusan B-02: waktu kejadian di lapangan dan waktu terima server dicatat
             *     terpisah. Timeline diurutkan dengan OccurredAt; status terkini ditentukan
             *     dengan Seq.
             */
            occurred_at?: string;
            occurred_at_adjusted?: boolean;
            reason?: string;
            received_at?: string;
            /**
             * @example late_after_final
             * @enum {string}
             */
            rejection_reason?: "late_after_final" | "out_of_order" | "pending_approval" | "cancellation_rejected" | "settlement_pending" | "settlement_decided";
            /** @example 42 */
            seq?: number;
            /**
             * @example in_progress
             * @enum {string}
             */
            to_status?: "requested" | "assigned" | "on_the_way" | "on_site" | "in_progress" | "completed" | "failed" | "cancelled";
        };
        "verifield-be_internal_modules_joborder_dto.PendingCancellation": {
            created_at?: string;
            id?: string;
            reason?: string;
            requested_by_name?: string;
            /**
             * @description Menentukan pertanyaan yang dihadapkan kepada koordinator: pembatalannya
             *     sendiri, atau penyelesaian komersial ketika pekerjaan sudah terlanjur
             *     selesai (keputusan B-10).
             * @example pending
             * @enum {string}
             */
            status?: "pending" | "pending_settlement";
        };
        "verifield-be_internal_modules_joborder_dto.SettleCancellationDTO": {
            /** @example Disepakati menagih separuh biaya kunjungan */
            note: string;
            /**
             * @example billed_partial
             * @enum {string}
             */
            outcome: "billed_full" | "billed_partial" | "waived";
        };
        "verifield-be_internal_modules_joborder_dto.SubmitStatusEventDTO": {
            /**
             * @description Keputusan B-03: penanda unik dibuat di perangkat sebelum kiriman pertama,
             *     sehingga tombol yang ditekan berulang kali saat sinyal lemah hanya
             *     menghasilkan satu baris riwayat.
             * @example 6f1e6f0c-6f2a-4c5e-9f3a-0b6b1a4d2c11
             */
            client_event_id: string;
            /**
             * @description Keputusan B-02: waktu saat tombol ditekan di lapangan, bukan saat
             *     laporan berhasil terkirim. Boleh kosong bila perangkat sedang online.
             */
            occurred_at?: string;
            /** @example Kargo belum tiba di dermaga */
            reason?: string;
            /**
             * @example on_site
             * @enum {string}
             */
            to_status: "on_the_way" | "on_site" | "in_progress" | "completed" | "failed";
        };
        "verifield-be_internal_modules_joborder_dto.SubmitStatusEventResult": {
            accepted?: boolean;
            duplicate?: boolean;
            event?: components["schemas"]["verifield-be_internal_modules_joborder_dto.JobStatusEventResponse"];
            message?: string;
            order?: components["schemas"]["verifield-be_internal_modules_joborder_dto.JobOrderResponse"];
        };
        "verifield-be_internal_modules_user_dto.CreateUserDTO": {
            /** @example siti@verifield.id */
            email: string;
            /** @example Siti Rahma */
            name: string;
            /** @example rahasia123 */
            password: string;
            /**
             * @example client
             * @enum {string}
             */
            role?: "admin" | "client" | "inspector" | "cs";
        };
        "verifield-be_internal_modules_user_dto.UpdateUserDTO": {
            /** @example siti@verifield.id */
            email?: string;
            /** @example true */
            is_active?: boolean;
            /** @example Siti Rahma */
            name?: string;
            /** @example rahasia123 */
            password?: string;
            /**
             * @example admin
             * @enum {string}
             */
            role?: "admin" | "client" | "inspector" | "cs";
        };
        "verifield-be_internal_modules_user_dto.UserResponse": {
            created_at?: string;
            /** @example siti@verifield.id */
            email?: string;
            /** @example 6f1e6f0c-6f2a-4c5e-9f3a-0b6b1a4d2c11 */
            id?: string;
            /** @example true */
            is_active?: boolean;
            /** @example Siti Rahma */
            name?: string;
            /** @example client */
            role?: string;
            updated_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
